import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: { '2xl': '1400px' },
    },
    extend: {
      colors: {
        primary: {
          DEFAULT: '#D4A853',
          light: '#F0DFA8',
          surface: '#FBF6E9',
          50: '#FBF6E9',
          100: '#F0DFA8',
          200: '#E8D494',
          300: '#E0C980',
          400: '#D8BE6C',
          500: '#D4A853',
          600: '#C49743',
          700: '#A67F38',
          800: '#88672D',
          900: '#6A4F22',
        },
        secondary: {
          DEFAULT: '#8FAE8B',
          light: '#C5D9C3',
          surface: '#F0F5EF',
          50: '#F0F5EF',
          100: '#C5D9C3',
          200: '#B5CCAF',
          300: '#A5BF9B',
          400: '#95B287',
          500: '#8FAE8B',
          600: '#7A9876',
          700: '#658261',
          800: '#506C4C',
          900: '#3B5637',
        },
        accent: {
          DEFAULT: '#E8B84B',
          50: '#FBF6E9',
          100: '#F5E9C8',
          200: '#F0DFA8',
          300: '#EDD388',
          400: '#EAC668',
          500: '#E8B84B',
          600: '#D4A43C',
          700: '#B88A32',
          800: '#9C7028',
          900: '#80561E',
        },
        success: { DEFAULT: '#6BA368', 50: '#F0F5EF' },
        warning: { DEFAULT: '#E8B84B', 50: '#FBF6E9' },
        destructive: { DEFAULT: '#D4655E', 50: '#FDF0ED' },
        background: '#F0F2F5',
        foreground: '#2C2C2C',
        muted: { DEFAULT: '#6B6B6B', foreground: '#A0A0A0' },
        card: { DEFAULT: '#FFFFFF', foreground: '#2C2C2C' },
        popover: { DEFAULT: '#FFFFFF', foreground: '#2C2C2C' },
        input: '#E8E6E1',
        border: '#E8E6E1',
        ring: '#D4A853',
      },
      fontFamily: {
        heading: ['Quicksand', 'sans-serif'],
        body: ['Nunito', 'Inter', 'sans-serif'],
      },
      borderRadius: {
        card: '12px',
      },
      boxShadow: {
        card: '0 4px 6px rgba(0,0,0,0.05)',
        'card-hover': '0 8px 25px rgba(0,0,0,0.1)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-in': { from: { opacity: '0', transform: 'translateY(10px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-out',
        'slide-in': 'slide-in 0.3s ease-out',
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
