ALTER TABLE "customizations"
ADD COLUMN "sidebar_bg" VARCHAR(7) NOT NULL DEFAULT '#1A1410',
ADD COLUMN "sidebar_text" VARCHAR(7) NOT NULL DEFAULT '#D1D5DB',
ADD COLUMN "sidebar_active_text" VARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN "bg_surface" VARCHAR(7) NOT NULL DEFAULT '#FFFFFF',
ADD COLUMN "bg_page" VARCHAR(7) NOT NULL DEFAULT '#FBF6E9',
ADD COLUMN "text_primary" VARCHAR(7) NOT NULL DEFAULT '#2C2C2C',
ADD COLUMN "text_secondary" VARCHAR(7) NOT NULL DEFAULT '#6B6B6B',
ADD COLUMN "border_color" VARCHAR(7) NOT NULL DEFAULT '#E5E7EB',
ADD COLUMN "table_header_bg" VARCHAR(7) NOT NULL DEFAULT '#F3F4F6',
ADD COLUMN "table_stripe_bg" VARCHAR(7) NOT NULL DEFAULT '#F9FAFB',
ADD COLUMN "table_hover_bg" VARCHAR(7) NOT NULL DEFAULT '#FBF6E9';
